### ISSUE TITLE
Create Moderation MVP Page

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutSPACEs#118]
### Summary

With respect to the [user flow diagram](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/platform-designs/user-flow), there must be a page that will be sued by moderators to be able to approve or reject stories that want to be made public. 

This should reflect the most basic version of the moderation process as seen in the [figma board](https://www.figma.com/file/HxqTSdeyAUNMualnBV0PET/Autspace-(WIP)?node-id=58%3A0).

### TODOs

- [x] Add Limited Navigation Bar at the top of the page
    - [x] Add Home button, which directs the user to the landing page.
    - [x] Add View Experiences button, which redirects user to current page.
        - (A placeholder URL will suffice.)
    - [x] Add `My Stories` button, which directs user to `My Stories` page (current page). 
        - Display *only* to signed-in user
        - [x] Redirects to `Home` page if page is reloaded after user logs out. 
    - [x] Add `Share Experiences` button, which directs user to view experiences page. 
        - (A placeholder URL will suffice.)
        - Display *only* to signed-in user
        - [x] Redirects to `Home` page if page is reloaded after user logs out. 
    - [x] Add  `Logout` button, which logs current user out. 
        - **Display only when the user has logged in.**
        - [x] Redirects to `Home` page if page is reloaded after user logs out. 
- [x] Add approve button
- [x] Add remove button
- [x] Add to navigation bar in overview page 
    - Should only appear after user has logged in.   

### Who can help?

Dev team! 

---

### Updates

Sowmya has almost finished this and will be send in a PR asap.

**Comment by lottycoupat** [comment]
@sowmya9507 please add to the issue if need be. Perhaps linking it to the pull request for this page?

**Comment by skfantoni** [comment]
Add categorisation options

Decisions that need to be made:
- [ ] At what point in the process does categorisation take place?
- [ ] Who decides what stories go under what categories?
- [ ] How are categories displayed on the site?
- [ ] Can users limit which categories they see and when?

**Comment by GeorgiaHCA** [comment]
Fabulous work! All the criteria are complete so I am opening a new issue for the second iteration and putting your comments there @skfantoni
