### ISSUE TITLE
Completing sign up flow

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#161]
## Description 
This ticket describes steps needed to complete the sign-up flow. 

The user scenarios are as follows: 
- A user signs up through the AutSPACEs webpage
- A user is directed to the AutSPACEs sign-up flow
- After a user has signed up, direct the user to the account survey questionnaire. 

## Definition of Done
A user is able to sign up through OpenHumans and direct the user to the account survey questionnaire. 

### Tasks
- [ ] On clicking sign-up, direct to the user to the OpenHumans sign-up page.
- [ ] On successful sign-up, direct the user to the account survey questionnaire.
   - [ ] Create a model storing the responses of the questionnaire
   - [ ] [Optional] Set a flag on the user model that describes if the user is new. 
       - [ ] After user completes questionnaire, set flag to true and do not show questionnaire again.
- [ ] When user is finished answering questionnaire, user should see confirmation navigation page.

**Comment by SuziQpid** [comment]
Also seems straightforward. Might be useful on sign in to warn a survey is part of the process and advise how many questions are in it. Some potential users may halt the sign in process if they think they don't have time to fill in a survey. Can they save first questions if they want to and return later.

**Comment by jhlink** [comment]
@SuziQpid , this is definitely something we want to raise in milestone 4, when accessibility and overall design of the website is reviewed, discussed, and reworked. 
Presently, there are only two questions that are asked when users sign up, but if they don't complete it and sign in later, they will not be given the questionnaire. This is probably a bug, but this will be clarified in milestone 4 after minimum functionality has been completed. (Some questions include... how would the user get to the questionnaire if they don't finish? Should it be presented even after the user signs in if they don't complete it? etc. etc.)

**Comment by callummole** [comment]
@gedankenstuecke this issue is tagged as Milestone 2, but is tracked by #140, which is Milestone 3. I'm happy to move it to Milestone 3, since it is involves data being moved between OH and the platform. Agree?

**Comment by gedankenstuecke** [comment]
Yep, that makes sense. Happy to have it moved!

**Comment by gedankenstuecke** [comment]
I closed #140 which was the broader issue, this one is still relevant as it's about the demographics capturing which we should as one of the next stages probably (and it doesn't block on anything else at this stage)

**Comment by gedankenstuecke** [comment]
I made a dedicated demographics issue #453
