### ISSUE TITLE
Add user role assignment via Django Admin

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#166]
## Description
User roles/permissions will be managed through the Django admin panel. An admin by default will be able to view, manipulate, and remove all data and users. However, the primary utility for feature will be assigning which users are moderators. 

### Tasks
Users use their OpenHumans credentials to utilize the site. 
- [x] Create a new or use the pre-existing users table, provided in the Django admin library, and create a foreign key on the OpenHumans user ID
- [x] Create a Moderator status
- [x] Allow admin to set a user as moderator
- [x] Allow admin to set a moderator as a user
- [ ] Add documentation on how to create an admin user for development

**Comment by SuziQpid** [comment]
This seems very straight forward. Congratulations. If l can get my head around this, most people will.

**Comment by anoura12** [comment]
@jhlink would the modboss/reviewer role be added to this issue as well or will that be a separate issue altogether?

**Comment by jhlink** [comment]
@anoura12 , please create a separate issue for this.

**Comment by callummole** [comment]
Closed in #420
