### ISSUE TITLE
Place-holder moderation page

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#20]
### Summary

Create a placeholder moderation page

### What needs to be done

- [ ] Make sure page is private to signed-in moderators (this links to #100, #102)
- [ ] **If an experience is submitted with share publicly permissions**, it should be automatically displayed on the moderator page (#99) (NB **all** experiences which are shared with "researcher" permissions should be automatically viewable by researchers without going through moderation. Only experiences with permission to be made "public" need to go through moderation.)
- [ ] option to approve or deny publication
- [ ] If approved, story needs to be displayed publicly
- [ ] Changes to story status; pending, approved and published, blocked should be updated on the "my stories" page for relevant user (#19)

### Who can help

* Anyone with web development skills to build
* Anyone from the community to review and test*
* the designs are already founded on substantial community feedback and user testing

**Comment by jhlink** [comment]
I don't think this should be part of the milestone 2. There aren't any simplified wireframes for this, but even if a placeholder is the only desirable feature, then my design suggestion would capitalizing Django's native support for an admin panel, which could be modified to meet all the moderator requirements. 

That said, the following items are simply out of scope for this milestone. 

```
- Make sure page is private to signed-in moderators (this links to #100, #102)
```
This implies that user levels have been implemented. We'll need to talk to Bastian about establishing user privileges in the OpenHumans database. Otherwise, there isn't a clear way to distinguish whether a signed in user is a moderator, a regular user, or a researcher. 

```
- If an experience is submitted with share publicly permissions, it should be automatically displayed on the moderator page (#99)
- Option to approve or deny publication 
- If approved, story needs to be displayed publicly
- Changes to story status; pending, approved and published, blocked should be updated on the "my stories" page for relevant user (#19)
```
These items imply features to implement for the moderator page. The placeholder I'm imagining is an empty web page that says "moderation". These features are not simply development tasks and should be capture in a separate milestone with wireframes describing their function and user flow.

**Comment by lottycoupat** [comment]
Decision to be made:

Which stories need to go through the moderation process:
- Only to research
- Only to AutSPACEs users
- To ALL public

@jhlink @GeorgiaHCA

**Comment by sowmya9507** [comment]
@lottycoupat will work on the creating of moderation page next!

**Comment by jhlink** [comment]
Cleaning up milestone 3 tickets. Moderation related tickets will be created shortly after all information has been aggregated. 
Closing.
