### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by soledadli** [alan-turing-institute/AutSPACEs#212]
## Summary

The current **Sign Up page** is not connected to the platform. Are we going to keep this page? If so, is there something else we want to include in the **sign-up process**?

![Screenshot 2022-01-11 at 11 02 14](https://user-images.githubusercontent.com/67457005/148954657-6fe9bf0e-7405-4267-9d96-fe5fb14e2a61.png)

@KirstieJane @GeorgiaHCA @BrainonSilicon 

## Related Issues 
* https://github.com/alan-turing-institute/AutSPACEs/issues/265

## Tasks
- [ ] Redesign the sign up form 
- [x] Set a condition for navigation template for the registration page
- [ ] Set up the backend

**Comment by GeorgiaHCA** [comment]
Thanks @soledadli ! I do think it is important to collect this information. We will need it to understand the experiences. I think we have two options, to collect the info when the user signs in or when they submit the story.

**Comment by GeorgiaHCA** [comment]
The former is much simpler for the user, the latter has some more flexibility especially if we are collecting other, optional demographic info which users might wish to share for some stories but not others.

**Comment by GeorgiaHCA** [comment]
I would recommend for the platform we deploy we should keep it simple and use a redesigned version of this page to test. Could it be supported in the backend trough adding an additional tag to the json file?

**Comment by GeorgiaHCA** [comment]
This also links to this issue: https://github.com/alan-turing-institute/AutisticaCitizenScience/issues/547. It will need furter consieration but maybe for a later version of the platform

**Comment by soledadli** [comment]
> alan-turing-institute/AutisticaCitizenScience#547

@GeorgiaHCA I will work on the re-design and include a simpler frontend form on the current platform for testing now.  For the backend set-up, I think it is definitely possible and we can bring it up to the meet-up tomorrow. 😄

**Comment by GeorgiaHCA** [comment]
Hiya @soledadli a few comments on this before we implement it

**Comment by GeorgiaHCA** [comment]
Apart from "Autism researcher"

**Comment by GeorgiaHCA** [comment]
"Medical professional, carer or social worker" instead of "Healthcare/medical worker for autistic person"

**Comment by GeorgiaHCA** [comment]
We should also allow people to say if they are autistic or not and whether they have a diagnosis or not separately as not all autistic people have a diagnosis (and not everyone diagnosed agrees with the diagnosis)

**Comment by GeorgiaHCA** [comment]
Final comment is there are a lot of potential additional pieces of information we may wish to collect, for instance to monitor gender and ethnic diversity, socio-economic etc., as well as co-occuring conditions. This is a next iteration probably though.

**Comment by gedankenstuecke** [comment]
At this point a duplicate of #265
