### ISSUE TITLE
Autism Glossary 

### ISSUE THREAD

**Issue by skfantoni** [alan-turing-institute/AutSPACEs#266]
## Summary

Deciding how to create the _Information Page_ glossary.

## Date Due by

Next Meet-Up Session 

## Details

I think this is one of the next things we should complete. We need to present it to the group and then we can use it as guidance for deciding what terminology is and isn’t acceptable in regards to the CoC.

## Tasks and Decisions

* [ ] Where do we want to a accumulate information from?
>* [ ] Academic Articles/Journals 
>* [ ] Medical Dictionary 
>* [ ] Charity information pages (ie. NAS)
>* [ ] Our own data 
* [ ] Do we want to include Pros _and_ Cons?
> This would be to specifically explain why some people may find certain terms offensive or upsetting (ie. Asperger, ASD, high-functioning etc.)
* [ ] How do we make it easily understandable to all?
>* [ ] Should we include a Layman version?
>* [ ] Would imaging help?
* [ ] Are we going to include terms that are no longer used?
* [ ] Do we want to write a **Red List** Glossary too

## Who can help

Anyone who wants to :)

**Comment by gedankenstuecke** [comment]
There was a duplication with the issue #378 which I have converted into a "discussion" rather than issue so that we can brainstorm more terms to be added.
