### ISSUE TITLE
Collect and plan all tasks that need to be carried out for the moderation process

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutSPACEs#267]
## Summary

We need to plan out all activities that will enable the moderation workstream to continue and keep up momentum. 

Therefore, please comment on this issue all activities you think will need to be carried out for the moderation process to be created successfully. These can be both by contributors who are developers (platform specific) or non-developers. 

## Date Due by

Ongoing. 

## Details

Each comment will be added to the below list and then planned out and actions assigned to contributors:

Planning/designing

* [x] A user flow defined for interaction with the platform and all other processes
* [ ] A recruitment of moderators process defined (including how many we will need)
* [ ] An onboarding of new moderators defined (including training/upskilling and materials)
* [x] A code of conduct including probably guidelines for useful andd ethical submissions (as well as strict rules)
* [ ] An escalation process with named responsible individuals
* [ ] User testing with a diverse autistic group

Operationalising

* [ ] A working moderation flow on the platform
* [ ] A number of autistic moderators who have been recruited and trained
* [ ] A process to support and iterate moderation as the platform continues to be used

Research

* [ ] Appropriate ethics approval for data on moderation
* [ ] Summaries of moderation sessions sent out, published on GitHub in anonymised form
* [ ] Write and submit a paper!

## Who can help

Anyone interested in moderation.
