### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#33]
### Summary

We need a clear and transparent roadmap in markdown linking to issuse, PRs, and deadlines. 

### What needs to be done? 

- [ ] Main steps to fully fledged platform worked out and outlined
- [ ] Time-tabled - feasible deadlines
- [ ] Appropriate milestones and labels created 
- [ ] Markdown file with roadmap created 
- [ ] Linked to milestones, issues, and project board
- [ ] Links to project management repository and other deadlines/issues (e.g. comms, moderation research, conferences, applications etc.)

**Comment by jhlink** [comment]
I think we should have a readme somewhere describing the roadmap in two week sprints, where each sprint we dedicate to some milestone. 
I really don't think issues for milestones need to be created until the current milestone is nearing completion. So, in this regard, items 5 and 6 are unnecessary. Items 1 and 2 are one and the same, and items 4 is a byproduct of the aforementioned task pairs. 

Presently, it crowds the issue tracker too much, and it can become difficult to pick out what needs to be done.

**Comment by jhlink** [comment]
Just a heads up, I expect milestone 1 to be completed this week, so we might need to have a conversation at some point about what needs to happen next.

**Comment by GeorgiaHCA** [comment]
Heya @lottycoupat - do you reeckon this issue is ready to close? I know you've done a lot of work on the Roadmap! :D

**Comment by lottycoupat** [comment]
@GeorgiaHCA Yes!!

**Comment by GeorgiaHCA** [comment]
Fab @lottycoupat !
