### ISSUE TITLE
Repo Refresh and Merge: Task tracking

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#359]
## Summary

Make sure the repo is in really good condition for further engagement/community building with project. This issue tracks all the tasks we need to complete for the repo refresh. 

## Date Due by

This is an ongoing process, but I'm going to aim to finish this iteration of tidying work by **1st November**

## Suggestions for tasks that can fix this issue

Tidying up

* [x] New filing structure for the AutSPACEs repo implemented
* [x] Files transferred from Autistica/Turing repo and are successfully merged
* [x] All issues are transferred to the AutSPACEs repo 
* [x] All issues are appropriately labelled, and attached to a Milestone
* [x] Every folder has a clear, current README
* [x] Make links are working - look out for 404s! 
* [x] All information up-to-date,
* [x] All data up-to-date - including Good form surveys
* [x] Check for typos, poor style, etc. 
* [x] Update labels and milestones
* [x] Any new applications, presentations, etc. uploaded
* [x] sort out/tidy up issues and PRs 
* [x] Make the READMEs and navigation routes clear and comprehensive to new people! 
* [x] Steps to involvement for different groups clear
* [ ] Process, progress, and build more clearly articulated and integrated 
* [ ] Get repo tested with different members of the community 

* [ ] (additional) - add anything new that would help with engagement or access. 

## Who can help

Anyone can help! Feel free to create PRs to fix any problems you find, or just leave a comment or make an issue for any problems you encounter you aren't sure how to fix.

*Autistic people are especially encouraged to help*  
You can also just comment on this issue below or email gaitkenhead@turing.ac.uk if anything is confusing or difficult for you to access.
