### ISSUE TITLE
Define Remaining Milestone 2 Tasks

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#93]
## Description
As it stands, integrating the file management demo has created a lot of progress. 
Need to define a document describing the simplified wireframe to be implemented to complete milestone 2.
Most are captured in the Milestone 2 label, however, it may be too much for incoming developers. 

### ToDos:
- [x] Write a doc within the platform-design file detailing the simplified MVP to be implemented in milestone 2
- [ ] Streamline development process in terms of assigning and reviewing tickets.
- [ ] Create tickets for every development task necessary for Milestone 2
    - [ ] Categorize tickets by page.

**Comment by GeorgiaHCA** [comment]
Heya @jhlink - is this something I could help with? I think there are a lot of labels around accessibility which may be confusing, but these could be done as a checklist at the end (maybe even as an addittional milestone?).

**Comment by jhlink** [comment]
@GeorgiaHCA , there are a number of accessibility issue tickets that are currently open. I think a good number of them may not be relevant to this current milestone, and I'm wondering if we can summarize/archive them so that we can look at them at a later date. Maybe when we complete milestone 3 or 4? 

I'd like to complete this issue ticket by Thursday, to be quite honest. 🤞 !!

**Comment by GeorgiaHCA** [comment]
Hiya @sowmya9507 are you able to input into this?

**Comment by GeorgiaHCA** [comment]
Hiya @jhlink - I've created a new milestone which contains the data-capture/data-management tasks relating to Open Humans and created a bunch of issues in this milestone which I've linked to the MVP issues which have a checklist for each page. This has been added to the WIP roadmap for development.  

Would also appreciate your throughts, @lottycoupat, @Islast, @gedankenstuecke, @sowmya9507, @BrainonSilicon, if any of you are able to take a look - just my first shot at it! 

If anyone has time please could you take a look at the Milestone 2 and 4 issues and comment for anything you think is missing/redundant/wrong/unclear?

Thanks <3
